### PR TITLE
Update old brick blockcodes in asset files to VS 1.20.0-rc1 equivalents 

### PR DESCRIPTION
**Pull request by zach2039**
The following remaps were done via script to all associated references within the `assets/` directory:

```
brickslabs-blue-down-free -> brickslabs-four-gray-down-free
brickslabs-blue-north-free -> brickslabs-four-gray-north-free
brickslabs-blue-south-free -> brickslabs-four-gray-south-free
claybricks-blue -> brickcourse-four-running-gray
claybricks-red -> brickcourse-four-running-red
clayshingleblock-blue -> clayshingleblock-gray
clayshinglestairs-blue-up-north-free -> clayshinglestairs-gray-up-north-free
```

These are similar remaps to those found in the `remap.json` file of VS, and should fix `Cannot load chiseled block id mapping for rotation` messages encountered in 1.20.0-rc1. All occurrences of the associated errors no longer appear in my `server-main.log` file after packaging and running a local copy of BetterRuins with this PR.

### CODE REVIEW

**Comment by AreYSerious** [comment]
Hello!
I really really appreciate that pull request but I already fixed those issues in our dev build some time ago 😊

https://github.com/AreYSerious/betterruins/commit/a345aa40033b23726828a5ae9f01c3aebe69c06a

**Comment by zach2039** [comment]
Sorry I missed that. Was hyper-focused on the log messages I forgot to check the last commit. Thanks!

**Comment by AreYSerious** [comment]
Aswell as all structures that contained new blocks or blocks that got affected by 1.20 already got updated.

We are actively working on the next update but since rc just released we need to get our new content polished to then get a nice and complete update out.

**Comment by AreYSerious** [comment]
> Sorry I missed that. Was hyper-focused on the log messages I forgot to check the last commit. Thanks!

Absolutely no problem I really appreciate the offer and the investment into helping tho tyvm it means a lot 👍

**Pull request closed without merging**
